#!/bin/bash
# Public HTTPS tunnels for the local stack. Run via:
#   screen -dmS dfi-tunnels bash scripts/start-https-tunnels.sh
#
# Mode comes from scripts/tunnel-config.sh (the single source of truth):
#   named — one cloudflared process serving two hostnames you own. Stable URLs.
#   quick — two cloudflared quick tunnels. New random hostnames every restart.
#
# Either way the resulting URLs are written to data/imports/tunnel-urls.env and
# sync-tunnel-env.sh then rewires frontend/.env.local + backend/.env, so the
# public URLs can never drift apart.
#
# This script only manages cloudflared. It never touches uvicorn (:8000) or
# next dev (:3001) — those belong to keep-local-stack.sh.
set -uo pipefail
export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/tunnel-config.sh"

BE_LOG=$LOGDIR/cloudflared-backend.log
FE_LOG=$LOGDIR/cloudflared-frontend.log
NAMED_LOG=$LOGDIR/cloudflared-named.log
CF_CONFIG=$HOME/.cloudflared/config-dfi.yml

mkdir -p "$LOGDIR"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

write_urls() {
  cat >"$URL_FILE" <<EENV
# Generated by scripts/start-https-tunnels.sh — single source of truth for
# the current public URLs. Consumed by scripts/sync-tunnel-env.sh.
TUNNEL_MODE=$TUNNEL_MODE
BACKEND_TUNNEL_URL=$1
FRONTEND_TUNNEL_URL=$2
EENV
  log "urls → $URL_FILE (be=$1 fe=$2)"
  bash "$SCRIPT_DIR/sync-tunnel-env.sh" || log "WARN sync-tunnel-env failed"
}

# ── Named mode: stable hostnames, one process, nothing to scrape ──────────────
if [ "$TUNNEL_MODE" = "named" ]; then
  if [ ! -f "$CF_CONFIG" ]; then
    log "ERROR TUNNEL_MODE=named but $CF_CONFIG is missing."
    log "      Run scripts/tunnel-named-setup.sh first (see docs/local-tunnels.md)."
    exit 1
  fi
  if [ -z "$NAMED_BE_HOSTNAME" ] || [ -z "$NAMED_FE_HOSTNAME" ]; then
    log "ERROR NAMED_BE_HOSTNAME / NAMED_FE_HOSTNAME unset in tunnel-config.sh"
    exit 1
  fi

  # Hostnames are known before the tunnel is even up, so wire env immediately.
  write_urls "https://$NAMED_BE_HOSTNAME" "https://$NAMED_FE_HOSTNAME"

  : >"$NAMED_LOG"
  while true; do
    log "running named tunnel '$NAMED_TUNNEL'"
    cloudflared --no-autoupdate tunnel --config "$CF_CONFIG" run >>"$NAMED_LOG" 2>&1
    log "named tunnel exited rc=$? — restarting in 5s"
    sleep 5
  done
fi

# ── Quick mode: random hostnames, scrape them out of the logs ────────────────
: >"$BE_LOG"
: >"$FE_LOG"

cloudflared --no-autoupdate tunnel --url "http://127.0.0.1:$BE_PORT" >>"$BE_LOG" 2>&1 &
BE_PID=$!
cloudflared --no-autoupdate tunnel --url "http://127.0.0.1:$FE_PORT" >>"$FE_LOG" 2>&1 &
FE_PID=$!
log "started quick tunnels be=$BE_PID fe=$FE_PID"

scrape() { grep -oE 'https://[a-zA-Z0-9-]+\.trycloudflare\.com' "$1" 2>/dev/null | head -1; }

for _ in $(seq 1 60); do
  BE_URL=$(scrape "$BE_LOG")
  FE_URL=$(scrape "$FE_LOG")
  if [ -n "$BE_URL" ] && [ -n "$FE_URL" ]; then
    write_urls "$BE_URL" "$FE_URL"
    break
  fi
  sleep 1
done

[ -n "${BE_URL:-}" ] && [ -n "${FE_URL:-}" ] || log "WARN quick tunnel URLs never appeared"

# Keep the screen session alive while the tunnels run.
wait
