#!/bin/bash
# One-time setup for STABLE public hostnames via a Cloudflare *named* tunnel.
#
# Quick tunnels (cloudflared tunnel --url) mint a new random
# *.trycloudflare.com hostname on every restart. A named tunnel binds to
# hostnames you own, so the public URLs survive restarts and reboots.
#
# Prerequisites (both are Cloudflare's, not ours):
#   1. A Cloudflare account (free plan is fine).
#   2. A domain whose DNS is managed by Cloudflare (nameservers delegated to
#      Cloudflare). Named tunnels cannot use trycloudflare.com hostnames.
#   3. A one-time browser login:  cloudflared tunnel login
#
# Usage:
#   scripts/tunnel-named-setup.sh example.com
#       → creates dfi.example.com (frontend) and dfi-api.example.com (backend)
#
#   scripts/tunnel-named-setup.sh app.example.com api.example.com
#       → uses exactly those two hostnames
#
# Keep hostnames to a single subdomain level. Cloudflare's Universal TLS cert
# covers example.com and *.example.com only; a.b.example.com would need a paid
# Advanced Certificate.
set -uo pipefail
export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/tunnel-config.sh"

CF_DIR=$HOME/.cloudflared
CERT=$CF_DIR/cert.pem
CONFIG=$CF_DIR/config-dfi.yml

die() { echo "ERROR: $*" >&2; exit 1; }

command -v cloudflared >/dev/null || die "cloudflared not on PATH"

# ── Step 1: the one interactive step we cannot do for you ─────────────────────
if [ ! -f "$CERT" ]; then
  cat <<'LOGIN'
────────────────────────────────────────────────────────────────────────────────
 One-time Cloudflare login required (this is the ONLY manual step)
────────────────────────────────────────────────────────────────────────────────

Run exactly this, in a terminal on this Mac Mini:

    cloudflared tunnel login

What happens, and what to click:

  1. A browser tab opens at dash.cloudflare.com.
  2. Log in / pick the Cloudflare account that owns your domain.
  3. Cloudflare shows "Select a domain" or "Authorize cloudflared" with a list
     of the zones (domains) on that account. Click your domain, then click the
     blue "Authorize" button.
  4. The tab says "You have successfully logged in" — close it.
  5. The terminal prints the path it wrote, and this file now exists:
         ~/.cloudflared/cert.pem

Then re-run this script with your domain:

    scripts/tunnel-named-setup.sh yourdomain.com

If step 3 shows NO domains, your Cloudflare account has no zone. Named tunnels
need one — see docs/local-tunnels.md for the fallback (keep quick tunnels and
leave OAUTH_MODE=localhost, which already keeps the Google Console values
stable forever).
────────────────────────────────────────────────────────────────────────────────
LOGIN
  exit 2
fi

echo "✓ found $CERT"

# ── Step 2: work out the two hostnames ────────────────────────────────────────
case $# in
  1)
    DOMAIN=$1
    FE_HOST="dfi.$DOMAIN"
    BE_HOST="dfi-api.$DOMAIN"
    ;;
  2)
    FE_HOST=$1
    BE_HOST=$2
    ;;
  *)
    die "usage: $0 <domain> | $0 <frontend-hostname> <backend-hostname>"
    ;;
esac

echo "  frontend → https://$FE_HOST  (local :$FE_PORT)"
echo "  backend  → https://$BE_HOST  (local :$BE_PORT)"

# ── Step 3: create the tunnel (idempotent) ────────────────────────────────────
if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$NAMED_TUNNEL"; then
  echo "✓ tunnel '$NAMED_TUNNEL' already exists"
else
  echo "creating tunnel '$NAMED_TUNNEL'"
  cloudflared tunnel create "$NAMED_TUNNEL" || die "tunnel create failed"
fi

TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v n="$NAMED_TUNNEL" '$2==n {print $1}' | head -1)
[ -n "$TUNNEL_ID" ] || die "could not resolve tunnel id for '$NAMED_TUNNEL'"
echo "✓ tunnel id $TUNNEL_ID"

# ── Step 4: ingress config — one tunnel serving both hostnames ────────────────
cat >"$CONFIG" <<YAML
# Generated by scripts/tunnel-named-setup.sh
tunnel: $TUNNEL_ID
credentials-file: $CF_DIR/$TUNNEL_ID.json
originRequest:
  noTLSVerify: true

ingress:
  - hostname: $FE_HOST
    service: http://127.0.0.1:$FE_PORT
  - hostname: $BE_HOST
    service: http://127.0.0.1:$BE_PORT
  - service: http_status:404
YAML
echo "✓ wrote $CONFIG"

# ── Step 5: DNS routes (CNAME → <id>.cfargotunnel.com) ────────────────────────
for host in "$FE_HOST" "$BE_HOST"; do
  if cloudflared tunnel route dns "$NAMED_TUNNEL" "$host" 2>&1 | tee /tmp/dfi-route.log | grep -qiE 'added|updated|created'; then
    echo "✓ DNS route $host"
  elif grep -qi 'already exists' /tmp/dfi-route.log; then
    echo "✓ DNS route $host (already present)"
  else
    echo "WARN could not route $host — check the Cloudflare dashboard DNS tab:"
    sed 's/^/      /' /tmp/dfi-route.log
  fi
done

# ── Step 6: flip the single source of truth over to named mode ────────────────
CONFIG_SH=$SCRIPT_DIR/tunnel-config.sh
TUNNEL_MODE=named \
NAMED_FE_HOSTNAME="$FE_HOST" \
NAMED_BE_HOSTNAME="$BE_HOST" \
CONFIG_SH="$CONFIG_SH" \
python3 - <<'PY'
import os
import re
from pathlib import Path

path = Path(os.environ["CONFIG_SH"])
text = path.read_text()
for key in ("TUNNEL_MODE", "NAMED_FE_HOSTNAME", "NAMED_BE_HOSTNAME"):
    value = os.environ[key]
    text = re.sub(
        rf"^{key}=\$\{{{key}:-[^}}]*\}}$",
        f"{key}=${{{key}:-{value}}}",
        text,
        flags=re.M,
    )
path.write_text(text)
PY
echo "✓ tunnel-config.sh switched to TUNNEL_MODE=named"

cat <<DONE

────────────────────────────────────────────────────────────────────────────────
 Named tunnel ready. Next:
────────────────────────────────────────────────────────────────────────────────
  1. Restart the tunnels (leaves backend/frontend untouched):
         screen -S dfi-tunnels -X quit 2>/dev/null
         screen -dmS dfi-tunnels bash $SCRIPT_DIR/start-https-tunnels.sh

  2. If you want OAuth on the public hostnames instead of localhost, set
     OAUTH_MODE=tunnel in scripts/tunnel-config.sh, re-run
     scripts/sync-tunnel-env.sh, and paste the two printed values into the
     Google Console once. They are stable from then on.
────────────────────────────────────────────────────────────────────────────────
DONE
